name: Web 2048 Application

on:
  push:
   branches: [ main ]
  pull_request:
    branches: [ main ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build & Push Image
      run: |
        echo "${{ secrets.YN }}" | docker login -u chathuracsddocker --password-stdin
        docker build -t chathuracsddocker/2048webgame/2048game:latest .
        docker push chathuracsddocker/2048webgame/2048webgame:latest
